[package]
name = "layouter"
version = "0.1.0"
authors = ["Nikolai Shalakin <nikolai.shalakin@lifeisfeudal.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "*"
ron = "*"